-- ============================
--derby工具： 
--1. 设置DERBY_HOME, 把bin目录加到PATH中即可 
--2. ij> connect 'jdbc:derby:example-derby'; run 'example-derby.sql'; 
--3. dblook -d 'jdbc:derby:example-derby' -o out.sql 
--4. startNetworkServer/stopNetworkServer
-- ----------------------------------------------

CREATE TABLE "APP"."IGNORE_THIS_TABLE" ("ID" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1));